openapi: 3.0.3
info:
  title: Swagger Poulstar Social Media - OpenAPI 3.0
  description: for learn swagger and yaml
  version: 1.0.0
tags:
  - name: User
    description: Everything about your Users
  - name: Post
    description: Everything about your Posts
  - name: Comment
    description: Everything about your Comments

components:
  securitySchemes:
    bearerAuth:
      type: http
      description: "Authorization: Bearer <token>"
      Authorization: Bearer <token>
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # ApiResponse
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: "##default"
    # Login
    Login:
      type: object
      properties:
        username:
          type: string
          description: phone or email
        password:
          type: password
          format: password
        grant_type:
          type: string
          enum: ["password"]
          default: "password"
        client_id:
          type: integer
          enum: [1]
          default: 1
        client_secret:
          type: string
          enum: ["PpYE2tplIoNkuwAU5T7mLcL7a1dBi6zdWt14iXjR"]
          default: "PpYE2tplIoNkuwAU5T7mLcL7a1dBi6zdWt14iXjR"

paths:
  /api/get-verify-code/{phone}:
    get:
      tags:
        - User
      summery: get login code
      description: get code for login
      parameters:
        - name: phone
          in: path
          description: Phone Number
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
  /oauth/token:
    post:
      tags:
        - User
      summery: Login user
      description: Login User Oauth
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
